name: Build Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build . --file ${{ inputs.dockerfile }} --tag ${{ inputs.image_name }}:${{ inputs.version }}
          docker push ${{ inputs.image_name }}:${{ inputs.version }}
