name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    # Specify Ubuntu version
    runs-on: ubuntu-24.04

    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Setup Python version (specify the desired version here)
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify Python version

      # Set up Node.js version (specify the desired version here)
      - name: Set up Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Specify Node.js version

      # Install Node.js packages for frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Set up Python environment and install Flask for backend
      - name: Set up Python environment for backend
        run: |
          cd backend
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file .github/Dockerfile --tag my-image-name:$(date +%s)
