name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [backend, frontend]
        include:
          - directory: backend
            dockerfile: .github/workflows/backend/Dockerfile
            image_name: zirahhh/wesync-backend
            version: '1.0'
          - directory: frontend
            dockerfile: .github/workflows/frontend/Dockerfile
            image_name: zirahhh/wesync-frontend
            version: '1.0'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . --file ${{ matrix.dockerfile }} --tag ${{ matrix.image_name }}:${{ matrix.version }}
          docker push ${{ matrix.image_name }}:${{ matrix.version }}
