name: Docker Image CI

on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  backend:
    if: contains(github.event.head_commit.message, 'backend')
    uses: ./.github/workflows/docker-image.yml
    with:
      image_name: zirahhh/wesync-backend
      dockerfile: backend/Dockerfile
      version: 1.0

  frontend:
    if: contains(github.event.head_commit.message, 'frontend')
    uses: ./.github/workflows/docker-image.yml
    with:
      image_name: zirahhh/wesync-frontend
      dockerfile: frontend/Dockerfile
      version: 1.0
